-- Esquema de ESTRESSE (Oracle): nomes fora de convenção de propósito. Rode num usuário/schema de TESTE.
BEGIN
  FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN ('TB_PED_ITM','TB_PED','TB_CLI','TB_SEM_REL')) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE "' || t.table_name || '" CASCADE CONSTRAINTS';
  END LOOP;
END;
/

CREATE TABLE TB_CLI (
  CODIGO       NUMBER(10) PRIMARY KEY,
  RAZAO_SOCIAL VARCHAR2(80) NOT NULL,
  UF           CHAR(2)
);

CREATE TABLE TB_PED (
  NUM_PED      NUMBER(10) PRIMARY KEY,
  CLI_COBRANCA NUMBER(10) REFERENCES TB_CLI(CODIGO),
  CLI_ENTREGA  NUMBER(10) REFERENCES TB_CLI(CODIGO),
  DT_PED       DATE,
  STATUS_PED   VARCHAR2(20)
);

CREATE TABLE TB_PED_ITM (
  SEQ        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COD_PED    NUMBER(10) NOT NULL REFERENCES TB_PED(NUM_PED),
  DESCR_ITEM VARCHAR2(80),
  QTD        NUMBER(10,2),
  VLR_UNIT   NUMBER(12,2)
);

CREATE TABLE TB_SEM_REL (A VARCHAR2(40), B VARCHAR2(40));

INSERT INTO TB_CLI VALUES (10,'ACME Ltda','MG');
INSERT INTO TB_CLI VALUES (20,'Globex SA','SP');
INSERT INTO TB_CLI VALUES (30,'Initech','RJ');
INSERT INTO TB_PED VALUES (1001,10,20,DATE '2026-09-01','ABERTO');
INSERT INTO TB_PED VALUES (1002,10,10,DATE '2026-09-05','FATURADO');
INSERT INTO TB_PED VALUES (1003,20,30,DATE '2026-09-07','ABERTO');
INSERT INTO TB_PED_ITM (COD_PED,DESCR_ITEM,QTD,VLR_UNIT) VALUES (1001,'Parafuso',10,1.5);
INSERT INTO TB_PED_ITM (COD_PED,DESCR_ITEM,QTD,VLR_UNIT) VALUES (1001,'Porca',20,0.8);
INSERT INTO TB_PED_ITM (COD_PED,DESCR_ITEM,QTD,VLR_UNIT) VALUES (1002,'Chave',1,35);
INSERT INTO TB_PED_ITM (COD_PED,DESCR_ITEM,QTD,VLR_UNIT) VALUES (1003,'Martelo',2,42.9);
INSERT INTO TB_PED_ITM (COD_PED,DESCR_ITEM,QTD,VLR_UNIT) VALUES (1003,'Prego',100,0.1);
INSERT INTO TB_SEM_REL VALUES ('x','y');
INSERT INTO TB_SEM_REL VALUES ('z','w');
COMMIT;
