import JSZip from 'jszip'

export function generateAppRouter(zip: JSZip, project: any, models: any[], uiViews: any[] = []) {
  const appFolder = zip.folder('src/app')
  const configFolder = zip.folder('src/config')
  if (!appFolder || !configFolder) return

  const projectName = project.name || 'Metabuilder App'

  // Freeze Navigation and Project Config
  const navigationGroups = Array.from(new Set(uiViews.map(v => v.group_name || 'Geral')))
  const navigation = navigationGroups.map(group => ({
    title: group,
    items: uiViews.filter(v => (v.group_name || 'Geral') === group).map(view => ({
      name: view.name,
      href: `/${view.slug}`,
      icon: view.logic_type === 'dashboard' ? 'Activity' : 'Database',
      logic_type: view.logic_type
    }))
  }))

  const projectConfig = {
    ...project,
    navigation
  }

  configFolder.file('project.json', JSON.stringify(projectConfig, null, 2))

  appFolder.file('globals.css', `@tailwind base;
@tailwind components;
@tailwind utilities;`)

  // Root Layout
  appFolder.file('layout.tsx', `import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CustomThemeProvider } from "@/components/CustomThemeProvider";
import { ProgressBarProvider } from "@/components/ProgressBarProvider";
import { I18nProvider } from "@/i18n/I18nContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "${projectName}",
  description: "Enterprise app generated by MetaBuilderPRO",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className={inter.className}>
        <CustomThemeProvider defaultTheme="light" attribute="class">
          <I18nProvider>
            <ProgressBarProvider />
            {children}
          </I18nProvider>
        </CustomThemeProvider>
      </body>
    </html>
  );
}
`)

  // Dashboard Group Layout (Sidebar navigation)
  const dashboardFolder = appFolder.folder('(dashboard)')
  if (dashboardFolder) {
    dashboardFolder.file('layout.tsx', `'use client'

import React, { Suspense } from 'react'
import { RuntimeLayoutClient } from '@/components/runtime/RuntimeLayoutClient'
import projectConfig from '@/config/project.json'

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return (
    <Suspense fallback={null}>
      <RuntimeLayoutClient 
        workspaceSlug="export"
        projectSlug="export"
        project={projectConfig}
        navigation={projectConfig.navigation}
        baseNavUrl=""
      >
        {children}
      </RuntimeLayoutClient>
    </Suspense>
  )
}
`)

    // Home Page inside (dashboard)
    dashboardFolder.file('page.tsx', `export default function Home() {
  return (
    <div className="flex flex-col items-center justify-center h-full text-center space-y-4">
      <div className="inline-flex items-center justify-center px-4 py-1.5 rounded-full bg-indigo-50 text-indigo-600 text-sm font-bold tracking-widest uppercase mb-4">
        MetaBuilderPRO Architecture
      </div>
      <h1 className="text-4xl font-black tracking-tight">
        Bem-vindo ao ${projectName}
      </h1>
      <p className="text-lg text-neutral-500 max-w-2xl mx-auto">
        Código fonte exportado com sucesso. Arquitetura Modular (FSD) pronta para ser escalada pelo seu time de desenvolvedores sêniores.
      </p>
      
      <div className="pt-8 grid grid-cols-1 md:grid-cols-2 gap-4 text-left max-w-3xl w-full">
        <div className="p-6 bg-white rounded-2xl shadow-sm border border-neutral-200">
          <h3 className="font-bold mb-2">📁 src/features</h3>
          <p className="text-sm text-neutral-500">Módulos isolados por domínio de negócio. Contém as regras de negócio, chamadas de API e componentes específicos.</p>
        </div>
        <div className="p-6 bg-white rounded-2xl shadow-sm border border-neutral-200">
          <h3 className="font-bold mb-2">📁 src/components/ui</h3>
          <p className="text-sm text-neutral-500">Componentes visuais agnósticos e reutilizáveis (Botões, Modais, Inputs), padrão Shadcn.</p>
        </div>
      </div>
    </div>
  );
}
`)

    // Generate Login Page
    const loginFolder = appFolder.folder('login')
    if (loginFolder) {
      loginFolder.file('page.tsx', `'use client'

import React from 'react'
import { LoginPortalClient } from '@/components/auth/LoginPortalClient'
import projectConfig from '@/config/project.json'
import { CustomThemeProvider } from '@/components/CustomThemeProvider'

export default function LoginPage() {
  const visual = (projectConfig.theme_config as any)?.ui_config || {}
  const auth = {
    allow_signup: visual.allow_signup || false,
    auth_type: (projectConfig as any).auth_type || 'none',
  }

  return (
    <div className="flex-1 min-h-screen bg-slate-50 dark:bg-[#050505]">
      <LoginPortalClient 
        project={projectConfig}
        workspaceSlug="export"
        projectSlug="export"
        locale="pt"
        visualConfig={visual}
        authConfig={auth}
      />
    </div>
  )
}
`)
    }
  }
}
