import JSZip from 'jszip'

export function generateAppRouter(zip: JSZip, project: any, models: any[], uiViews: any[] = []) {
  const appFolder = zip.folder('src/app')
  const configFolder = zip.folder('src/config')
  if (!appFolder || !configFolder) return

  const projectName = project.name || 'Metabuilder App'

  // Freeze Navigation and Project Config
  const navigationGroups = Array.from(new Set(uiViews.map(v => v.group_name || 'Geral')))
  const navigation = navigationGroups.map(group => ({
    title: group,
    items: uiViews.filter(v => (v.group_name || 'Geral') === group).map(view => ({
      name: view.name,
      href: `/${view.slug}`,
      icon: view.logic_type === 'dashboard' ? 'Activity' : 'Database',
      logic_type: view.logic_type
    }))
  }))

  const projectConfig = {
    ...project,
    navigation
  }

  configFolder.file('project.json', JSON.stringify(projectConfig, null, 2))

  appFolder.file('globals.css', `@tailwind base;
@tailwind components;
@tailwind utilities;`)

  // Root Layout
  appFolder.file('layout.tsx', `import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CustomThemeProvider } from "@/components/CustomThemeProvider";
import { ProgressBarProvider } from "@/components/ProgressBarProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "${projectName}",
  description: "Enterprise app generated by MetaBuilderPRO",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className={inter.className}>
        <CustomThemeProvider defaultTheme="system" attribute="class">
          <ProgressBarProvider />
          {children}
        </CustomThemeProvider>
      </body>
    </html>
  );
}
`)

  // Dashboard Group Layout (Sidebar navigation)
  const dashboardFolder = appFolder.folder('(dashboard)')
  if (dashboardFolder) {
    dashboardFolder.file('layout.tsx', `'use client'

import React from 'react'
import { RuntimeLayoutClient } from '@/components/runtime/RuntimeLayoutClient'
import projectConfig from '@/config/project.json'

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return (
    <RuntimeLayoutClient 
      workspace={{ slug: 'export', name: 'Local' }}
      project={projectConfig}
      navigation={projectConfig.navigation}
    >
      {children}
    </RuntimeLayoutClient>
  )
}
`)

    // Home Page inside (dashboard)
    dashboardFolder.file('page.tsx', `export default function Home() {
  return (
    <div className="flex flex-col items-center justify-center h-full text-center space-y-4">
      <div className="inline-flex items-center justify-center px-4 py-1.5 rounded-full bg-indigo-50 text-indigo-600 text-sm font-bold tracking-widest uppercase mb-4">
        MetaBuilderPRO Architecture
      </div>
      <h1 className="text-4xl font-black tracking-tight">
        Bem-vindo ao ${projectName}
      </h1>
      <p className="text-lg text-neutral-500 max-w-2xl mx-auto">
        Código fonte exportado com sucesso. Arquitetura Modular (FSD) pronta para ser escalada pelo seu time de desenvolvedores sêniores.
      </p>
      
      <div className="pt-8 grid grid-cols-1 md:grid-cols-2 gap-4 text-left max-w-3xl w-full">
        <div className="p-6 bg-white rounded-2xl shadow-sm border border-neutral-200">
          <h3 className="font-bold mb-2">📁 src/features</h3>
          <p className="text-sm text-neutral-500">Módulos isolados por domínio de negócio. Contém as regras de negócio, chamadas de API e componentes específicos.</p>
        </div>
        <div className="p-6 bg-white rounded-2xl shadow-sm border border-neutral-200">
          <h3 className="font-bold mb-2">📁 src/components/ui</h3>
          <p className="text-sm text-neutral-500">Componentes visuais agnósticos e reutilizáveis (Botões, Modais, Inputs), padrão Shadcn.</p>
        </div>
      </div>
    </div>
  );
}
`)

    // Create a dynamic route for each ui_view
    uiViews.forEach(view => {
      const viewRoute = dashboardFolder.folder(view.slug)
      if (viewRoute) {
        
        // Se a view está associada a um model (ex: CRUD ou Use Case Avançado)
        if (view.model_id) {
          const model = models.find(m => m.id === view.model_id)
          if (model) {
            viewRoute.file('page.tsx', `import { ${model.name.replace(/\s/g, '')}List } from "@/features/${model.table_name}/components/${model.name.replace(/\s/g, '')}List"
import { fetch${model.name.replace(/\s/g, '')}s } from "@/features/${model.table_name}/actions"

export default async function ${view.slug.replace(/-/g, '')}Page() {
  const data = await fetch${model.name.replace(/\s/g, '')}s()

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-bold tracking-tight">${view.name}</h2>
        <p className="text-neutral-500">Gerencie os registros de ${view.name.toLowerCase()}</p>
      </div>
      <${model.name.replace(/\s/g, '')}List initialData={data} viewConfig={${JSON.stringify(view.layout_config || view.draft_config?.layout_config || {})}} />
    </div>
  )
}
`)
            return
          }
        }

        // Se não tiver model_id (ex: Dashboards), gera um skeleton premium
        viewRoute.file('page.tsx', `export default function ${view.slug.replace(/-/g, '')}Page() {
  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-bold tracking-tight">${view.name}</h2>
        <p className="text-neutral-500">Página customizada ou Dashboard</p>
      </div>
      
      <div className="bg-white dark:bg-neutral-900 border border-neutral-200/60 dark:border-neutral-800 p-12 rounded-2xl shadow-sm text-center">
        <h3 className="text-lg font-medium text-neutral-900 dark:text-white mb-2">Área de Desenvolvimento</h3>
        <p className="text-neutral-500 text-sm max-w-md mx-auto">
          Esta view não possui um modelo de dados associado. Insira seus componentes customizados (BYOC) ou dashboards aqui.
        </p>
      </div>
    </div>
  )
}
`)
      }
    })
  }
}
