import JSZip from 'jszip'

export function generateAppRouter(zip: JSZip, project: any, models: any[], uiViews: any[] = [], authStrategy: string = 'managed', projectRelations: any[] = []) {
  const appFolder = zip.folder('src/app')
  const configFolder = zip.folder('src/config')
  if (!appFolder || !configFolder) return

  const projectName = project.name || 'Metabuilder App'

  // Fallback Navigation generation if project doesn't have custom navigation defined
  const navigationGroups = Array.from(new Set(uiViews.map(v => v.group_name || 'Geral')))
  const fallbackNavigation = navigationGroups.map((group, idx) => ({
    id: `group-${idx}`,
    label: group,
    icon: 'Folder',
    type: 'folder',
    target: '',
    children: uiViews.filter(v => (v.group_name || 'Geral') === group).map(view => ({
      id: view.id || view.slug,
      label: view.name,
      icon: view.logic_type === 'dashboard' ? 'Activity' : 'Database',
      type: 'view',
      target: view.slug
    }))
  }))

  const projectConfig = {
    ...project,
    models: models,
    navigation: (project.navigation && Array.isArray(project.navigation) && project.navigation.length > 0) 
      ? project.navigation 
      : fallbackNavigation,
    relations: projectRelations.map((r: any) => {
      const childModel = models.find((m: any) => m.id === r.from_model_id)
      const fkField = childModel?.fields?.find((f: any) => f.id === r.from_field_id)
      return {
        ...r,
        master_model_id: r.to_model_id,
        detail_model_id: r.from_model_id,
        foreign_key: fkField?.db_column_name || ''
      }
    })
  }

  configFolder.file('project.json', JSON.stringify(projectConfig, null, 2))

  appFolder.file('globals.css', `@tailwind base;
@tailwind components;
@tailwind utilities;`)

  // Root Layout
  appFolder.file('layout.tsx', `import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CustomThemeProvider } from "@/components/CustomThemeProvider";
import { ProgressBarProvider } from "@/components/ProgressBarProvider";
import { I18nProvider } from "@/i18n/I18nContext";
import { ToastProvider } from "@/components/ui/Toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "${projectName}",
  description: "Enterprise app generated by MetaBuilderPRO",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className={inter.className}>
        <CustomThemeProvider defaultTheme="light" attribute="class">
          <I18nProvider>
            <ProgressBarProvider />
            <ToastProvider>
              {children}
            </ToastProvider>
          </I18nProvider>
        </CustomThemeProvider>
      </body>
    </html>
  );
}
`)

  // Dashboard Group Layout (Sidebar navigation)
  const dashboardFolder = appFolder.folder('(dashboard)')
  if (dashboardFolder) {
    dashboardFolder.file('layout.tsx', `'use client'

import React, { Suspense } from 'react'
import { RuntimeLayoutClient } from '@/components/runtime/RuntimeLayoutClient'
import projectConfig from '@/config/project.json'

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return (
    <Suspense fallback={null}>
      <RuntimeLayoutClient 
        workspaceSlug="export"
        projectSlug="export"
        project={projectConfig as any}
        navigation={(projectConfig.navigation as any) || []}
        baseNavUrl=""
        isNoAuth={${authStrategy === 'none'}}
      >
        {children}
      </RuntimeLayoutClient>
    </Suspense>
  )
}
`)

    // Home Page inside (dashboard)
    dashboardFolder.file('page.tsx', `
import projectConfig from '@/config/project.json'
import { DynamicDashboard } from '@/components/runtime/DynamicDashboard'

export default function Home() {
  return (
    <div className="flex-1 overflow-y-auto">
      <DynamicDashboard 
        items={(projectConfig.navigation as any) || []}
        workspaceSlug="export"
        projectSlug="export"
        title="Dashboard"
        subtitle="Bem-vindo ao sistema"
        icon="LayoutDashboard"
        breadcrumbs={[]}
        baseNavUrl=""
      />
    </div>
  )
}
`)

    // Central de Downloads Page inside (dashboard)
    const downloadsFolder = dashboardFolder.folder('downloads')
    if (downloadsFolder) {
      downloadsFolder.file('page.tsx', `
import React from 'react'
import { DownloadsManagerClient } from '@/components/runtime/DownloadsManagerClient'
import projectConfig from '@/config/project.json'

export default function DownloadsPage() {
  return (
    <div className="flex-1 overflow-y-auto w-full h-full p-4 lg:p-8">
      <div className="max-w-7xl mx-auto h-full">
        <DownloadsManagerClient 
          workspaceSlug="export"
          projectSlug="export"
          projectId={projectConfig.id}
          userId="00000000-0000-0000-0000-000000000000"
        />
      </div>
    </div>
  )
}
`)
    }

    // Generate Login Page
    const loginFolder = appFolder.folder('login')
    if (loginFolder) {
      loginFolder.file('page.tsx', `'use client'

import React from 'react'
import { LoginPortalClient } from '@/components/auth/LoginPortalClient'
import projectConfig from '@/config/project.json'
import { CustomThemeProvider } from '@/components/CustomThemeProvider'

export default function LoginPage() {
  const visual = (projectConfig.theme_config as any)?.ui_config || {}
  const auth = {
    allow_signup: visual.allow_signup || false,
    auth_type: (projectConfig as any).auth_type || 'none',
  }

  return (
    <div className="flex-1 min-h-screen bg-slate-50 dark:bg-[#050505]">
      <LoginPortalClient 
        project={projectConfig}
        workspaceSlug=""
        projectSlug={(projectConfig as any).slug || ''}
        locale="pt"
        visualConfig={visual}
        authConfig={auth}
        isCustomDomain={true}
      />
    </div>
  )
}
`)
    }
  }
}
