import JSZip from 'jszip'

export function generateRootFiles(zip: JSZip, project: any, dataMode: string = 'supabase', authStrategy: string = 'managed') {
  const security = project.theme_config?.security || { traditional_login: true, mfa_enabled: false, passkey_enabled: false }

  zip.file('package.json', JSON.stringify({
    name: project.slug || 'metabuilder-app',
    version: '1.0.0',
    private: true,
    description: 'Project generated by MetaBuilderPRO - Enterprise Architecture',
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'next lint'
    },
    dependencies: {
      'next': '^14.2.26',
      'react': '^18',
      'react-dom': '^18',
      'lucide-react': '^0.395.0',
      'clsx': '^2.1.1',
      'tailwind-merge': '^2.3.0',
      'next-themes': '^0.3.0',
      'date-fns': '^3.6.0',
      'framer-motion': '^12.38.0',
      'recharts': '^3.8.1',
      '@dnd-kit/core': '^6.3.1',
      '@dnd-kit/sortable': '^10.0.0',
      '@dnd-kit/utilities': '^3.2.2',
      'next-nprogress-bar': '^2.4.7',
      '@supabase/supabase-js': '^2.43.4',
      '@supabase/ssr': '^0.3.0',
      ...(dataMode === 'postgres' ? { 'pg': '^8.11.5' } : {}),
      '@simplewebauthn/browser': '^13.3.0',
      '@simplewebauthn/server': '^13.3.1',
      '@xyflow/react': '^12.10.2',
      'dagre': '^0.8.5',
      'leaflet': '^1.9.4',
      'react-leaflet': '^4.2.1',
      'otplib': '^13.4.1',
      'qrcode': '^1.5.4',
      'qrcode.react': '^4.2.0',
      ...(authStrategy === 'legacy' || authStrategy === 'ldap' ? { 'jose': '^5.4.0' } : {}),
      ...(authStrategy === 'ldap' ? { 'ldapjs': '^3.0.7' } : {})
    },
    devDependencies: {
      'typescript': '^5',
      '@types/node': '^20',
      '@types/react': '^18',
      '@types/react-dom': '^18',
      'postcss': '^8',
      'tailwindcss': '^3.4.1',
      '@types/dagre': '^0.7.54',
      '@types/leaflet': '^1.9.21',
      '@types/qrcode': '^1.5.6',
      ...(dataMode === 'postgres' ? { '@types/pg': '^8.11.5' } : {}),
      ...(authStrategy === 'ldap' ? { '@types/ldapjs': '^3.0.5' } : {})
    }
  }, null, 2))

  zip.file('tsconfig.json', JSON.stringify({
    compilerOptions: {
      target: "es2015",
      downlevelIteration: true,
      lib: ["dom", "dom.iterable", "esnext"],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: "esnext",
      moduleResolution: "bundler",
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: "preserve",
      incremental: true,
      plugins: [{ name: "next" }],
      paths: { "@/*": ["./src/*"] }
    },
    include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
    exclude: ["node_modules"]
  }, null, 2))

  zip.file('tailwind.config.ts', `import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
export default config;
`)

  zip.file('postcss.config.mjs', `/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    tailwindcss: {},
  },
};
export default config;
`)
}

export function generateEnv(zip: JSZip, project: any, dataMode: string = 'supabase', authStrategy: string = 'managed', dbConfig: any = null) {
  let supaUrl = dbConfig?.supabaseUrl ? dbConfig.supabaseUrl : 'https://your-project.supabase.co'
  let supaAnon = dbConfig?.supabaseAnonKey ? dbConfig.supabaseAnonKey : 'your_supabase_anon_key'

  // If using Tunnel for anything, inject Central MetaBuilder credentials
  if (dataMode === 'tunnel' || authStrategy === 'tunnel') {
    supaUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || supaUrl
    supaAnon = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || supaAnon
  }

  let envContent = `# Authentication
NEXT_PUBLIC_SUPABASE_URL=${supaUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${supaAnon}

# Project Token
META_PROJECT_TOKEN=${project.secret_token || 'your_project_token'}
`

  if (dataMode === 'postgres') {
    const user = dbConfig?.user || 'postgres'
    const password = dbConfig?.password || 'senha'
    const host = dbConfig?.host || 'localhost'
    const port = dbConfig?.port || '5432'
    const database = dbConfig?.database || `${project.slug || 'app'}_db`
    const connectionString = `postgresql://${user}:${password}@${host}:${port}/${database}`

    envContent += `
# Database Connection
DATABASE_URL=${connectionString}
`
  }

  if (authStrategy === 'legacy' || authStrategy === 'ldap') {
    envContent += `
# JWT Session Secret
JWT_SECRET=super-secret-key-replace-me-in-production
`
  }

  if (authStrategy === 'ldap') {
    envContent += `
# LDAP Configuration
LDAP_URL=ldap://10.0.0.15:389
LDAP_BASE_DN=dc=empresa,dc=local
LDAP_BIND_DN=cn=admin,dc=empresa,dc=local
LDAP_BIND_PASSWORD=admin_password
`
  }

  envContent += `
# Export Manager Configuration
# Defina a pasta onde os arquivos XLS/JSON gerados em background serão salvos e lidos pelo Gerenciador de Downloads
LOCAL_DOWNLOAD_PATH=C:\\AgTech\\DownloadsMetaBuilder
`

  const envFileName = dbConfig ? '.env.local' : '.env.example'
  zip.file(envFileName, envContent)

  if (envFileName !== '.env.example') {
    zip.file('.env.example', envContent)
  }
}
