import JSZip from 'jszip'

export function generateRootFiles(zip: JSZip, project: any, dbType: string = 'supabase') {
  const security = project.theme_config?.security || { traditional_login: true, mfa_enabled: false, passkey_enabled: false }

  zip.file('package.json', JSON.stringify({
    name: project.slug || 'metabuilder-app',
    version: '1.0.0',
    private: true,
    description: 'Project generated by MetaBuilderPRO - Enterprise Architecture',
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'next lint'
    },
    dependencies: {
      'next': '14.2.4',
      'react': '^18',
      'react-dom': '^18',
      'lucide-react': '^0.395.0',
      'clsx': '^2.1.1',
      'tailwind-merge': '^2.3.0',
      '@supabase/supabase-js': '^2.43.4',
      '@supabase/ssr': '^0.3.0',
      ...(dbType === 'postgres' ? { 'pg': '^8.11.5' } : {}),
      ...(security.passkey_enabled ? { '@simplewebauthn/browser': '^9.0.1' } : {})
    },
    devDependencies: {
      'typescript': '^5',
      '@types/node': '^20',
      '@types/react': '^18',
      '@types/react-dom': '^18',
      'postcss': '^8',
      'tailwindcss': '^3.4.1',
      ...(dbType === 'postgres' ? { '@types/pg': '^8.11.5' } : {})
    }
  }, null, 2))

  zip.file('tsconfig.json', JSON.stringify({
    compilerOptions: {
      lib: ["dom", "dom.iterable", "esnext"],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: "esnext",
      moduleResolution: "bundler",
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: "preserve",
      incremental: true,
      plugins: [{ name: "next" }],
      paths: { "@/*": ["./src/*"] }
    },
    include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
    exclude: ["node_modules"]
  }, null, 2))

  zip.file('tailwind.config.ts', `import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
export default config;
`)

  zip.file('postcss.config.mjs', `/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    tailwindcss: {},
  },
};
export default config;
`)
}

export function generateEnv(zip: JSZip, project: any, dbType: string = 'supabase') {
  let envContent = `# Authentication
NEXT_PUBLIC_SUPABASE_URL=your_supabase_url
NEXT_PUBLIC_SUPABASE_ANON_KEY=your_supabase_anon_key

# Project Token
META_PROJECT_TOKEN=${project.secret_token || 'your_project_token'}
`

  if (dbType === 'postgres') {
    envContent += `
# Database Connection
DATABASE_URL=postgresql://postgres:senha@localhost:5432/${project.slug || 'app'}_db
`
  }

  zip.file('.env.example', envContent)
}
