import JSZip from 'jszip'

export function generateRootFiles(zip: JSZip, project: any, dataMode: string = 'supabase', authStrategy: string = 'managed', legacyDriver: string = '') {
  const security = project.theme_config?.security || { traditional_login: true, mfa_enabled: false, passkey_enabled: false }

  zip.file('package.json', JSON.stringify({
    name: project.slug || 'metabuilder-app',
    version: '1.0.0',
    private: true,
    description: 'Project generated by MetaBuilderPRO - Enterprise Architecture',
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'next lint'
    },
    dependencies: {
      'next': '^14.2.26',
      'react': '^18',
      'react-dom': '^18',
      'lucide-react': '^0.395.0',
      'clsx': '^2.1.1',
      'tailwind-merge': '^2.3.0',
      'next-themes': '^0.3.0',
      'date-fns': '^3.6.0',
      'framer-motion': '^12.38.0',
      'recharts': '^3.8.1',
      'react-is': '^18.3.1 || ^19.0.0',
      '@dnd-kit/core': '^6.3.1',
      '@dnd-kit/sortable': '^10.0.0',
      '@dnd-kit/utilities': '^3.2.2',
      'next-nprogress-bar': '^2.4.7',
      '@supabase/supabase-js': '^2.43.4',
      '@supabase/ssr': '^0.10.2',
      ...(dataMode === 'postgres' || legacyDriver === 'postgres' ? { 'pg': '^8.11.5' } : {}),
      ...(dataMode === 'oracle' || legacyDriver === 'oracle' ? { 'oracledb': '^6.6.0' } : {}),
      '@simplewebauthn/browser': '^13.3.0',
      '@simplewebauthn/server': '^13.3.1',
      '@xyflow/react': '^12.10.2',
      'dagre': '^0.8.5',
      'leaflet': '^1.9.4',
      'react-leaflet': '^4.2.1',
      'otplib': '^13.4.1',
      'qrcode': '^1.5.4',
      'qrcode.react': '^4.2.0',
      ...(authStrategy === 'legacy' || authStrategy === 'ldap' ? { 'jose': '^5.4.0', 'bcryptjs': '^2.4.3' } : {}),
      ...(authStrategy === 'ldap' ? { 'ldapjs': '^3.0.7' } : {})
    },
    devDependencies: {
      'typescript': '^5',
      '@types/node': '^20',
      '@types/react': '^18',
      '@types/react-dom': '^18',
      'postcss': '^8',
      'tailwindcss': '^3.4.1',
      '@types/dagre': '^0.7.54',
      '@types/leaflet': '^1.9.21',
      '@types/qrcode': '^1.5.6',
      ...(dataMode === 'postgres' || legacyDriver === 'postgres' ? { '@types/pg': '^8.11.5' } : {}),
      ...(authStrategy === 'legacy' || authStrategy === 'ldap' ? { '@types/bcryptjs': '^2.4.6' } : {}),
      ...(authStrategy === 'ldap' ? { '@types/ldapjs': '^3.0.5' } : {})
    }
  }, null, 2))

  zip.file('tsconfig.json', JSON.stringify({
    compilerOptions: {
      target: "es2015",
      downlevelIteration: true,
      lib: ["dom", "dom.iterable", "esnext"],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: "esnext",
      moduleResolution: "bundler",
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: "preserve",
      incremental: true,
      plugins: [{ name: "next" }],
      paths: { "@/*": ["./src/*"] }
    },
    include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
    exclude: ["node_modules"]
  }, null, 2))

  zip.file('tailwind.config.ts', `import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
export default config;
`)

  zip.file('postcss.config.mjs', `/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    tailwindcss: {},
  },
};
export default config;
`)

  zip.file('.gitignore', `# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.

# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.pnpm-debug.log*

# local env files
.env*.local
.env
.env.development.local
.env.test.local
.env.production.local

# vercel
.vercel
`)
}

export function generateEnv(zip: JSZip, project: any, dataMode: string = 'supabase', authStrategy: string = 'managed', legacyDriver: string = 'supabase', dbConfig: any = null) {
  let supaUrl = dbConfig?.supabaseUrl?.trim() ? dbConfig.supabaseUrl.trim() : 'https://your-project.supabase.co'
  let supaAnon = dbConfig?.supabaseAnonKey?.trim() ? dbConfig.supabaseAnonKey.trim() : 'your_supabase_anon_key'

  // If using Tunnel for anything, inject Central MetaBuilder credentials
  if (dataMode === 'tunnel' || authStrategy === 'tunnel') {
    supaUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || supaUrl
    supaAnon = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || supaAnon
  }

  // Only include Supabase credentials when they are actually needed.
  // For legacy/ldap auth modes the app authenticates via its own API route (/api/auth/login)
  // and never calls Supabase Auth. Emitting the placeholder URL causes the safe-client guard
  // to miss the stub (URL starts with 'https://') and attempt a real Supabase connection,
  // which fails and breaks login.
  const needsSupabase = authStrategy === 'managed' || dataMode === 'supabase' || dataMode === 'tunnel' || authStrategy === 'tunnel'

  let envContent = needsSupabase
    ? `# Authentication
NEXT_PUBLIC_SUPABASE_URL=${supaUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${supaAnon}

# Export Flag
NEXT_PUBLIC_IS_EJECTED_APP=true

# Project Token
META_PROJECT_TOKEN=${project.secret_token || 'your_project_token'}
`
    : `# Authentication (Supabase not used in this auth mode)
# NEXT_PUBLIC_SUPABASE_URL=  <- not required for legacy/ldap auth
# NEXT_PUBLIC_SUPABASE_ANON_KEY=  <- not required for legacy/ldap auth

# Project Token
META_PROJECT_TOKEN=${project.secret_token || 'your_project_token'}
`

  if (dbConfig || dataMode === 'postgres' || dataMode === 'legacy' || dataMode === 'oracle' || dataMode === 'mysql') {
    let connectionString = dbConfig?.url || ''
    
    if (!connectionString) {
      const user = dbConfig?.user || 'postgres'
      const password = dbConfig?.password || 'senha'
      const host = dbConfig?.host || 'localhost'
      const port = dbConfig?.port || (legacyDriver === 'postgres' ? '5432' : legacyDriver === 'oracle' ? '1521' : legacyDriver === 'mysql' ? '3306' : legacyDriver === 'sqlserver' ? '1433' : '5432')
      const database = dbConfig?.database || `${project.slug || 'app'}_db`
      
      if (legacyDriver === 'oracle') {
        connectionString = `oracle://${user}:${password}@${host}:${port}/${database}`
      } else if (legacyDriver === 'mysql') {
        connectionString = `mysql://${user}:${password}@${host}:${port}/${database}`
      } else if (legacyDriver === 'sqlserver') {
        connectionString = `sqlserver://${host}:${port};database=${database};user=${user};password=${password};`
      } else {
        connectionString = `postgresql://${user}:${password}@${host}:${port}/${database}`
      }
    }

    envContent += `
# Database Connection
DATABASE_URL="${connectionString}"
`
  }

  if (authStrategy === 'legacy' || authStrategy === 'ldap') {
    envContent += `
# JWT Session Secret
JWT_SECRET=super-secret-key-replace-me-in-production
`
  }

  if (authStrategy === 'ldap') {
    envContent += `
# LDAP Configuration
LDAP_URL=ldap://10.0.0.15:389
LDAP_BASE_DN=dc=empresa,dc=local
LDAP_BIND_DN=cn=admin,dc=empresa,dc=local
LDAP_BIND_PASSWORD=admin_password
`
  }

  envContent += `
# Export Manager Configuration
# Defina a pasta onde os arquivos XLS/JSON gerados em background serão salvos e lidos pelo Gerenciador de Downloads
LOCAL_DOWNLOAD_PATH=C:\\AgTech\\DownloadsMetaBuilder
`

  let envExample = `# Authentication
NEXT_PUBLIC_SUPABASE_URL=https://your-project.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=your_supabase_anon_key

# Project Token
META_PROJECT_TOKEN=your_project_token
`
  if (dbConfig || dataMode === 'postgres' || dataMode === 'legacy' || dataMode === 'oracle' || dataMode === 'mysql') {
    let dummyString = 'postgresql://user:password@localhost:5432/dbname'
    if (legacyDriver === 'oracle') dummyString = 'oracle://user:password@localhost:1521/dbname'
    else if (legacyDriver === 'mysql') dummyString = 'mysql://user:password@localhost:3306/dbname'
    else if (legacyDriver === 'sqlserver') dummyString = 'sqlserver://localhost:1433;database=dbname;user=user;password=password;'
    
    envExample += `
# Database Connection
DATABASE_URL="${dummyString}"
`
  }

  if (authStrategy === 'legacy' || authStrategy === 'ldap') {
    envExample += `
# JWT Session Secret
JWT_SECRET=super-secret-key-replace-me-in-production
`
  }

  if (authStrategy === 'ldap') {
    envExample += `
# LDAP Configuration
LDAP_URL=ldap://10.0.0.15:389
LDAP_BASE_DN=dc=empresa,dc=local
LDAP_BIND_DN=cn=admin,dc=empresa,dc=local
LDAP_BIND_PASSWORD=admin_password
`
  }

  envExample += `
# Export Manager Configuration
LOCAL_DOWNLOAD_PATH=C:\\AgTech\\DownloadsMetaBuilder
`

  const envFileName = '.env.local'
  zip.file(envFileName, envContent)
  zip.file('.env.example', envExample)
}
