import { AppAST, WorkspaceAST } from './ast'
import { generateRoutes } from './layers/routes'
import { generateActions } from './layers/actions'
import { generateComponents } from './layers/components'
import { generatePortalPage, generateWorkspaceLayout, generateWorkspaceGlobalCss, generateProjectLayout } from './layers/portal'

/**
 * emitter.ts
 *
 * Recebe a AST (Árvore Abstrata) e orquestra a geração de todos os arquivos
 * do projeto Next.js em um mapa de string (Memory FS).
 */

export function generateNativeProject(ast: AppAST): Map<string, string> {
  const files = new Map<string, string>()

  // 1. Arquivos Base do Projeto
  generateBaseFiles(ast, files)

  // 2. Geração das Camadas
  generateRoutes(ast, files)
  generateActions(ast, files)
  generateComponents(ast, files)

  return files
}

function generateBaseFiles(ast: AppAST, files: Map<string, string>) {
  // package.json
  files.set('package.json', JSON.stringify({
    name: ast.projectName.toLowerCase().replace(/[^a-z0-9]/g, '-'),
    version: "1.0.0",
    private: true,
    scripts: {
      "dev": "next dev",
      "build": "next build",
      "start": "next start"
    },
    dependencies: {
      "next": "^14.2.0",
      "react": "^18.3.0",
      "react-dom": "^18.3.0",
      "lucide-react": "^0.360.0",
      "clsx": "^2.1.0",
      "tailwind-merge": "^2.2.0",
      "react-hook-form": "^7.51.0",
      "@hookform/resolvers": "^3.3.4",
      "zod": "^3.22.4",
      "@radix-ui/react-label": "^2.0.2",
      "@radix-ui/react-slot": "^1.0.2",
      "@radix-ui/react-tabs": "^1.0.4",
      ...(ast.dbStack === 'supabase' 
          ? { "@supabase/ssr": "^0.3.0", "@supabase/supabase-js": "^2.40.0" }
          : ast.dbStack === 'oracle'
            ? { "oracledb": "^6.5.0" }
            : ast.dbStack === 'mysql'
              ? { "mysql2": "^3.9.0" }
              : ast.dbStack === 'sqlserver'
                ? { "mssql": "^10.0.0" }
                : { "pg": "^8.11.0" })
    },
    devDependencies: {
      "typescript": "^5.0.0",
      "@types/node": "^20",
      "@types/react": "^18",
      "@types/react-dom": "^18",
      "tailwindcss": "^3.4.0",
      "postcss": "^8.4.0"
    }
  }, null, 2))

  // .env.local
  if (ast.dbStack === 'supabase') {
    files.set('.env.local', `NEXT_PUBLIC_SUPABASE_URL="${ast.supabaseUrl || ''}"\nNEXT_PUBLIC_SUPABASE_ANON_KEY="${ast.supabaseAnonKey || ''}"`)
  } else if (ast.dbStack === 'oracle') {
    files.set('.env.local', `DB_CONNECTION_STRING="${ast.dbConnectionString || 'localhost:1521/XEPDB1'}"\nDB_USER="admin"\nDB_PASSWORD="password"`)
  } else if (ast.dbStack === 'mysql') {
    files.set('.env.local', `DATABASE_URL="${ast.dbConnectionString || 'mysql://user:password@localhost:3306/db_name'}"`)
  } else if (ast.dbStack === 'sqlserver') {
    files.set('.env.local', `DATABASE_URL="${ast.dbConnectionString || 'Server=localhost,1433;Database=db_name;User Id=user;Password=password;Encrypt=true'}"`)
  } else {
    files.set('.env.local', `DATABASE_URL="${ast.dbConnectionString || 'postgres://user:pass@localhost:5432/db'}"`)
  }

  // .gitignore
  files.set('.gitignore', `# dependencies
/node_modules
/.pnp
.pnp.js

# next.js
/.next/
/out/

# misc
.DS_Store

# local env files
.env*.local
.env
`)

  // tailwind.config.ts
  files.set('tailwind.config.ts', `import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
      },
    },
  },
  plugins: [],
};
export default config;
`)

  // globals.css
  files.set('app/globals.css', `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --background: #ffffff;
  --foreground: #171717;
}

@media (prefers-color-scheme: dark) {
  :root {
    --background: #0a0a0a;
    --foreground: #ededed;
  }
}

body {
  color: var(--foreground);
  background: var(--background);
}`)

  // Root Layout
  files.set('app/layout.tsx', `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${ast.projectName}",
  description: "Generated by MetaBuilder PRO CleanCodeGenerator",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>{children}</body>
    </html>
  );
}
`)

  // Root Page (Home temporária)
  files.set('app/page.tsx', `import Link from 'next/link'

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <h1 className="text-4xl font-bold mb-8">Bem-vindo ao ${ast.projectName}</h1>
      <p className="mb-4">Código gerado com sucesso!</p>
      
      <div className="flex gap-4">
        ${ast.routes.map(r => `<Link href="${r.path}" className="text-blue-500 hover:underline">
          Acessar ${r.title}
        </Link>`).join('\n        ')}
      </div>
    </main>
  )
}
`)
}

/**
 * generateWorkspaceProject
 *
 * Recebe uma WorkspaceAST e produz um único projeto Next.js com:
 *  - Portal de entrada (/) com cards de todos os projetos
 *  - Sub-rotas por projeto (/[slug]/...)
 *  - Server Actions e componentes isolados por projeto
 */
export function generateWorkspaceProject(ast: WorkspaceAST): Map<string, string> {
  const files = new Map<string, string>()

  // 1. Arquivos raiz do workspace (layout, globals, portal page)
  files.set('app/layout.tsx', generateWorkspaceLayout(ast))
  files.set('app/globals.css', generateWorkspaceGlobalCss())
  files.set('app/page.tsx', generatePortalPage(ast))

  // 2. package.json unificado (dependências de todos os projetos)
  const allDeps: Record<string, string> = {
    'next': '^14.2.0',
    'react': '^18.3.0',
    'react-dom': '^18.3.0',
    'lucide-react': '^0.360.0',
    'clsx': '^2.1.0',
    'tailwind-merge': '^2.2.0',
  }
  if (ast.projects.some(p => p.app.dbStack === 'supabase')) {
    allDeps['@supabase/ssr'] = '^0.3.0'
    allDeps['@supabase/supabase-js'] = '^2.40.0'
  }
  if (ast.projects.some(p => p.app.dbStack === 'postgres'))   allDeps['pg'] = '^8.11.0'
  if (ast.projects.some(p => p.app.dbStack === 'mysql'))      allDeps['mysql2'] = '^3.9.0'
  if (ast.projects.some(p => p.app.dbStack === 'sqlserver'))  allDeps['mssql'] = '^10.0.0'
  if (ast.projects.some(p => p.app.dbStack === 'oracle'))     allDeps['oracledb'] = '^6.5.0'

  files.set('package.json', JSON.stringify({
    name: ast.workspaceSlug,
    version: '1.0.0',
    private: true,
    scripts: { dev: 'next dev', build: 'next build', start: 'next start' },
    dependencies: allDeps,
    devDependencies: {
      typescript: '^5.0.0',
      '@types/node': '^20',
      '@types/react': '^18',
      '@types/react-dom': '^18',
      tailwindcss: '^3.4.0',
      postcss: '^8.4.0',
    },
  }, null, 2))

  // 3. .env.local com credenciais do workspace
  if (ast.dbStack === 'supabase') {
    files.set('.env.local', `NEXT_PUBLIC_SUPABASE_URL="${ast.supabaseUrl || ''}"\nNEXT_PUBLIC_SUPABASE_ANON_KEY="${ast.supabaseAnonKey || ''}"`)
  } else {
    files.set('.env.local', `DATABASE_URL="${ast.dbConnectionString || ''}"`)
  }

  // .gitignore
  files.set('.gitignore', `/node_modules\n/.next\n/out\n.DS_Store\n.env*.local\n.env\n`)

  // tailwind.config.ts
  files.set('tailwind.config.ts', `import type { Config } from 'tailwindcss';\nconst config: Config = {\n  content: ['./app/**/*.{js,ts,jsx,tsx,mdx}', './components/**/*.{js,ts,jsx,tsx,mdx}'],\n  theme: { extend: {} },\n  plugins: [],\n};\nexport default config;\n`)

  // 4. Por projeto: layout + rotas + actions + components
  for (const project of ast.projects) {
    const pSlug = project.slug
    const pApp = project.app

    // Layout do projeto (sidebar com as rotas dele)
    const routeNav = pApp.routes.map(r => ({ path: r.path, title: r.title }))
    files.set(`app/${pSlug}/layout.tsx`, generateProjectLayout(project.name, pSlug, routeNav))

    // Página índice do projeto (redirect para primeira view)
    const firstRoute = pApp.routes[0]?.path || '/'
    files.set(`app/${pSlug}/page.tsx`, `import { redirect } from 'next/navigation';\nexport default function ProjectIndex() {\n  redirect('/${pSlug}${firstRoute}');\n}\n`)

    // Rotas, Actions e Components — com prefix do projeto
    const projectFiles = new Map<string, string>()
    generateRoutes(pApp, projectFiles)
    generateActions(pApp, projectFiles)
    generateComponents(pApp, projectFiles)

    // Reprefixa todos os arquivos para ficarem dentro de app/[slug]/
    for (const [path, content] of projectFiles) {
      const newPath = path.replace(/^app\//, `app/${pSlug}/`)
      files.set(newPath, content)
    }
  }

  return files
}
