import JSZip from 'jszip'

export class SourceCodeGenerator {
  private zip: JSZip
  private project: any
  private models: any[]

  constructor(project: any, models: any[]) {
    this.zip = new JSZip()
    this.project = project
    this.models = models
  }

  public async generate(): Promise<Buffer> {
    this.generateRootFiles()
    this.generateAppRouter()
    this.generateFeatures()
    this.generateLib()
    this.generateEnv()

    return await this.zip.generateAsync({ type: 'nodebuffer' })
  }

  private generateRootFiles() {
    const security = this.project.theme_config?.security || { traditional_login: true, mfa_enabled: false, passkey_enabled: false }

    this.zip.file('package.json', JSON.stringify({
      name: this.project.slug || 'metabuilder-app',
      version: '1.0.0',
      private: true,
      description: 'Project generated by MetaBuilderPRO - Enterprise Architecture',
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
        lint: 'next lint'
      },
      dependencies: {
        'next': '14.2.4',
        'react': '^18',
        'react-dom': '^18',
        'lucide-react': '^0.395.0',
        'clsx': '^2.1.1',
        'tailwind-merge': '^2.3.0',
        '@supabase/supabase-js': '^2.43.4',
        '@supabase/ssr': '^0.3.0',
        ...(security.passkey_enabled ? { '@simplewebauthn/browser': '^9.0.1' } : {})
      },
      devDependencies: {
        'typescript': '^5',
        '@types/node': '^20',
        '@types/react': '^18',
        '@types/react-dom': '^18',
        'postcss': '^8',
        'tailwindcss': '^3.4.1'
      }
    }, null, 2))

    this.zip.file('tsconfig.json', JSON.stringify({
      compilerOptions: {
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./src/*"] }
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"]
    }, null, 2))

    this.zip.file('tailwind.config.ts', `import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
export default config;
`)

    this.zip.file('postcss.config.mjs', `/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    tailwindcss: {},
  },
};
export default config;
`)

    this.zip.file('.env.example', `# Authentication
NEXT_PUBLIC_SUPABASE_URL=your_supabase_url
NEXT_PUBLIC_SUPABASE_ANON_KEY=your_supabase_anon_key

# Project Token
META_PROJECT_TOKEN=${this.project.secret_token || 'your_project_token'}
`)
  }

  private generateAppRouter() {
    const appFolder = this.zip.folder('src/app')
    if (!appFolder) return

    const projectName = this.project.name || 'Metabuilder App'

    appFolder.file('globals.css', `@tailwind base;\n@tailwind components;\n@tailwind utilities;`)

    appFolder.file('layout.tsx', `import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "${projectName}",
  description: "Enterprise app generated by MetaBuilderPRO",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
`)

    appFolder.file('page.tsx', `import { ArrowRight } from 'lucide-react'
import Link from 'next/link'

export default function Home() {
  return (
    <main className="min-h-screen flex flex-col items-center justify-center bg-neutral-50 text-neutral-900 p-8">
      <div className="max-w-2xl w-full space-y-8 text-center">
        <div className="inline-flex items-center justify-center px-4 py-1.5 rounded-full bg-indigo-50 text-indigo-600 text-sm font-bold tracking-widest uppercase mb-4">
          MetaBuilderPRO Architecture
        </div>
        <h1 className="text-5xl font-black tracking-tight">
          ${projectName}
        </h1>
        <p className="text-lg text-neutral-500 font-medium">
          Código fonte exportado com sucesso. Arquitetura Modular (FSD) pronta para ser escalada pelo seu time de desenvolvedores sêniores.
        </p>
        
        <div className="pt-8 grid grid-cols-1 md:grid-cols-2 gap-4 text-left">
          <div className="p-6 bg-white rounded-2xl shadow-sm border border-neutral-200">
            <h3 className="font-bold mb-2">📁 src/features</h3>
            <p className="text-sm text-neutral-500">Módulos isolados por domínio de negócio. Contém as regras de negócio, chamadas de API e componentes específicos.</p>
          </div>
          <div className="p-6 bg-white rounded-2xl shadow-sm border border-neutral-200">
            <h3 className="font-bold mb-2">📁 src/components/ui</h3>
            <p className="text-sm text-neutral-500">Componentes visuais agnósticos e reutilizáveis (Botões, Modais, Inputs), padrão Shadcn.</p>
          </div>
        </div>
      </div>
    </main>
  );
}
`)
  }

  private generateFeatures() {
    const featuresFolder = this.zip.folder('src/features')
    if (!featuresFolder) return

    // Create a feature folder for each database model
    this.models.forEach(model => {
      const featFolder = featuresFolder.folder(model.table_name)
      if (!featFolder) return

      // API Layer (Server Actions)
      const apiFolder = featFolder.folder('api')
      apiFolder?.file('actions.ts', `// Server Actions for ${model.name}
'use server'

import { createClient } from '@/lib/supabase/server'

export async function fetch${model.name.replace(/\\s/g, '')}s() {
  const supabase = await createClient()
  const { data, error } = await supabase.from('${model.table_name}').select('*')
  if (error) throw new Error(error.message)
  return data
}
`)

      // UI Components specific to this feature
      const componentsFolder = featFolder.folder('components')
      componentsFolder?.file(`${model.name.replace(/\\s/g, '')}List.tsx`, `'use client'

import React from 'react'

export function ${model.name.replace(/\\s/g, '')}List({ data }: { data: any[] }) {
  return (
    <div className="space-y-4">
      {data.map(item => (
        <div key={item.id} className="p-4 border rounded-lg bg-white">
          <pre className="text-xs">{JSON.stringify(item, null, 2)}</pre>
        </div>
      ))}
    </div>
  )
}
`)

      // Business Logic / Services
      const servicesFolder = featFolder.folder('services')
      servicesFolder?.file(`${model.table_name}.service.ts`, `// Domain Service Layer (Agnostic to UI)
// Implement complex business rules here for ${model.name}

export class ${model.name.replace(/\\s/g, '')}Service {
  static validateBusinessRule(data: any) {
    // ... validation logic
    return true
  }
}
`)

      // Hooks
      const hooksFolder = featFolder.folder('hooks')
      hooksFolder?.file(`use${model.name.replace(/\\s/g, '')}.ts`, `'use client'
import { useState } from 'react'

export function use${model.name.replace(/\\s/g, '')}() {
  const [isLoading, setIsLoading] = useState(false)
  // ... local state logic
  return { isLoading }
}
`)
    })
  }

  private generateLib() {
    const libFolder = this.zip.folder('src/lib')
    if (!libFolder) return

    libFolder.file('utils.ts', `import { type ClassValue, clsx } from 'clsx'
import { twMerge } from 'tailwind-merge'

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
`)

    const supabaseFolder = libFolder.folder('supabase')
    supabaseFolder?.file('server.ts', `import { createServerClient, type CookieOptions } from '@supabase/ssr'
import { cookies } from 'next/headers'

export async function createClient() {
  const cookieStore = cookies()

  return createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get(name: string) {
          return cookieStore.get(name)?.value
        },
        set(name: string, value: string, options: CookieOptions) {
          try {
            cookieStore.set({ name, value, ...options })
          } catch (error) {}
        },
        remove(name: string, options: CookieOptions) {
          try {
            cookieStore.set({ name, value: '', ...options })
          } catch (error) {}
        },
      },
    }
  )
}
`)
  }

  private generateEnv() {
    this.zip.file('.env.example', `NEXT_PUBLIC_SUPABASE_URL=your-project-url
NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key
SUPABASE_SERVICE_ROLE_KEY=your-service-role-key
`)
  }
}
